# Generated by Django 4.2.1 on 2026-03-20 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Motif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название мотива')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL-слаг')),
                ('content', models.TextField(blank=True, verbose_name='Легенда и значение')),
                ('image', models.CharField(blank=True, default='', max_length=255, verbose_name='Путь к картинке')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Время изменения')),
                ('is_published', models.BooleanField(choices=[(0, 'Черновик'), (1, 'Опубликовано')], default=1, verbose_name='Статус публикации')),
            ],
            options={
                'verbose_name': 'Мотив',
                'verbose_name_plural': 'Мотивы',
                'ordering': ['-time_create'],
                'indexes': [models.Index(fields=['-time_create'], name='irezumi_mot_time_cr_765bc4_idx')],
            },
        ),
    ]
