# Generated by Django 4.2.1 on 2026-04-03 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('irezumi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Категория')),
                ('slug', models.SlugField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='TagPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(db_index=True, max_length=100, verbose_name='Тег')),
                ('slug', models.SlugField(max_length=255, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='motif',
            name='views_count',
            field=models.IntegerField(default=0, verbose_name='Просмотры'),
        ),
        migrations.AddField(
            model_name='motif',
            name='cat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='motifs', to='irezumi.category', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='motif',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='motifs', to='irezumi.tagpost', verbose_name='Теги'),
        ),
    ]
