# Generated by Django 4.2.1 on 2026-04-17 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('irezumi', '0002_category_tagpost_motif_views_count_motif_cat_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tagpost',
            options={'verbose_name': 'Тег', 'verbose_name_plural': 'Теги'},
        ),
    ]
