# Generated by Django 4.2.1 on 2026-05-13 10:09

from django.db import migrations, models
import irezumi.models


class Migration(migrations.Migration):

    dependencies = [
        ('irezumi', '0003_alter_tagpost_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motif',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=irezumi.models.get_image_path, verbose_name='Изображение мотива'),
        ),
    ]
