# Generated by Django 4.2.1 on 2026-03-20 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя мастера')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('century', models.IntegerField(verbose_name='Век')),
                ('bio', models.TextField(blank=True, verbose_name='Биография')),
            ],
            options={
                'ordering': ['century', 'name'],
            },
        ),
    ]
