# Generated by Django 4.2.1 on 2026-04-03 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Studio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название студии')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес (Город)')),
            ],
        ),
        migrations.AddField(
            model_name='master',
            name='studio',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='master', to='masters.studio', verbose_name='Студия'),
        ),
    ]
