# Generated by Django 4.2.1 on 2026-04-17 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0002_studio_master_studio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='master',
            options={'ordering': ['century', 'name'], 'verbose_name': 'Мастер', 'verbose_name_plural': 'Мастера'},
        ),
        migrations.AlterModelOptions(
            name='studio',
            options={'verbose_name': 'Студия', 'verbose_name_plural': 'Студии'},
        ),
    ]
